version: 1.5.{build}
image: Visual Studio 2017


environment:
  matrix:
  - PlatformToolset: v140_xp
  - PlatformToolset: v141_xp

platform:
    #- x64
    - Win32

configuration:
    - Unicode Release
    - Unicode Debug

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x64" set platform_input=x64

    - if "%platform%"=="Win32" set archi=x86
    - if "%platform%"=="Win32" set platform_input=Win32

    - if "%PlatformToolset%"=="v140_xp" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %archi%
    - if "%PlatformToolset%"=="v141_xp" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%


build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"\GmodLua\vcbuild\
    - msbuild vcbuild.vcxproj /m /p:configuration="%configuration%" /p:platform="%platform_input%" /p:PlatformToolset="%PlatformToolset%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-

        if ($env:PLATFORM_INPUT -eq "x64") {
            Push-AppveyorArtifact "GmodLua\vcbuild\$env:PLATFORM\$env:CONFIGURATION\HexEditor.dll" -FileName HexEditor.dll
        }

        if ($env:PLATFORM_INPUT -eq "Win32" ) {
            Push-AppveyorArtifact "GmodLua\vcbuild\$env:CONFIGURATION\HexEditor.dll" -FileName HexEditor.dll
        }

        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release" -and $env:PLATFORMTOOLSET -eq "v141_xp") {
            if($env:PLATFORM_INPUT -eq "x64"){
            $ZipFileName = "HexEditor_$($env:APPVEYOR_REPO_TAG_NAME)_x64.zip"
            7z a $ZipFileName "$($env:APPVEYOR_BUILD_FOLDER)\GmodLua\vcbuild\$env:PLATFORM_INPUT\$env:CONFIGURATION\*.dll"
            }
            if($env:PLATFORM_INPUT -eq "Win32"){
            $ZipFileName = "HexEditor_$($env:APPVEYOR_REPO_TAG_NAME)_x86.zip"
            7z a $ZipFileName "$($env:APPVEYOR_BUILD_FOLDER)\GmodLua\vcbuild\$env:CONFIGURATION\*.dll"
            }
        }

artifacts:
  - path: HexEditor_*.zip
    name: releases

deploy:
    provider: GitHub
    auth_token:
        secure: PhNXrhw03Z0rJZssX/UYyoIofw669wU1GBy/hGq+WJPCXd7mbxDu6Il32Rx0LBH6
    artifact: releases
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
        PlatformToolset: v141_xp
        configuration: Release
